### ISSUE TITLE
ZMQ exception=Again('Resource temporarily unavailable')>

### ISSUE THREAD

**Issue by brianoflondon** [Podcastindex-org/podping-hivewriter#2]
While testing with dockerised versions on my iMac and sending URLs from a terminal hive-watcher, ZMQ now seems to be a bit touchy?

I am running it in full debug mode inside Docker inside VSCode so I'm hesitant to say this is a real problem, but perhaps there is more we need to do around error trapping on the ZMQ bit.

I'm just restarting it all again (in full debug) to see if this crops up again.

```
2021-06-14 09:38:59,147 INFO root MainThread : Duration: 6.267 - URL in queue: https://feeds.buzzsprout.com/1106981.rss - URL List: 2
2021-06-14 09:38:59,149 INFO root MainThread : Duration: 6.269 - URL in queue: https://feeds.buzzsprout.com/888925.rss - URL List: 3
2021-06-14 09:39:04,506 ERROR asyncio MainThread : Task exception was never retrieved
future: <Task finished coro=<zmq_response_loop() done, defined at src/podping_hivewriter/hive_writer.py:341> exception=Again('Resource temporarily unavailable')>
Traceback (most recent call last):
  File "src/podping_hivewriter/hive_writer.py", line 353, in zmq_response_loop
    url: str = await socket.recv_string()
  File "/usr/local/lib/python3.7/site-packages/zmq/_future.py", line 464, in _handle_recv
    result = recv(**kwargs)
  File "zmq/backend/cython/socket.pyx", line 781, in zmq.backend.cython.socket.Socket.recv
  File "zmq/backend/cython/socket.pyx", line 817, in zmq.backend.cython.socket.Socket.recv
  File "zmq/backend/cython/socket.pyx", line 191, in zmq.backend.cython.socket._recv_copy
  File "zmq/backend/cython/socket.pyx", line 186, in zmq.backend.cython.socket._recv_copy
  File "zmq/backend/cython/checkrc.pxd", line 22, in zmq.backend.cython.checkrc._check_rc
zmq.error.Again: Resource temporarily unavailable
2021-06-14 09:39:14,165 INFO root MainThread : Size of Urls: 129
2021-06-14 09:39:14,166 INFO root MainThread : Received num_urls: 3
2021-06-14 09:39:14,636 INFO root MainThread : Transaction sent: 39c5791b71f6c73cbee3b4dbd13d4ce1f4fb8818 - Num urls: 3 - Size of Urls: 119 - Json size: 172
2021-06-14 09:39:14,636 INFO root MainThread : Overhead: 53
2021-06-14 09:39:14,637 INFO root MainThread : Task time: 0.47 - Queue size: 0
2021-06-14 09:39:14,637 INFO root MainThread : Finished a task: 39c5791b71f6c73cbee3b4dbd13d4ce1f4fb8818 - 0

```
BTW even running in full Debug on VSCode while just doing normal podping loads (not catching up) it's using sub 1% CPU and 65Mb of Ram. This this is very efficient.

**Comment by brianoflondon** [comment]
OK after leaving it running (again in the debug) the same thing did happen:

```
2021-06-14 10:28:31,871 INFO root MainThread : Finished a task: 7dcb3be0a3bf7445da851430b74c7d528138625c - 0
2021-06-14 10:28:49,325 INFO root MainThread : Duration: 0.000 - URL in queue: https://feeds.buzzsprout.com/1428532.rss - URL List: 1
2021-06-14 10:28:49,327 INFO root MainThread : Duration: 2.860 - URL in queue: https://feeds.buzzsprout.com/1755998.rss - URL List: 2
2021-06-14 10:28:52,331 INFO root MainThread : Size of Urls: 87
2021-06-14 10:28:52,332 INFO root MainThread : Received num_urls: 2
2021-06-14 10:28:52,771 INFO root MainThread : Transaction sent: 0054012f12bfab1904fc40f085de2f1d3ef5ac72 - Num urls: 2 - Size of Urls: 80 - Json size: 129
2021-06-14 10:28:52,771 INFO root MainThread : Overhead: 49
2021-06-14 10:28:52,771 INFO root MainThread : Task time: 0.44 - Queue size: 0
2021-06-14 10:28:52,772 INFO root MainThread : Finished a task: 0054012f12bfab1904fc40f085de2f1d3ef5ac72 - 0
2021-06-14 10:29:06,377 ERROR asyncio MainThread : Task exception was never retrieved
future: <Task finished coro=<zmq_response_loop() done, defined at src/podping_hivewriter/hive_writer.py:343> exception=Again('Resource temporarily unavailable')>
Traceback (most recent call last):
  File "src/podping_hivewriter/hive_writer.py", line 355, in zmq_response_loop
    url: str = await socket.recv_string()
  File "/usr/local/lib/python3.7/site-packages/zmq/_future.py", line 464, in _handle_recv
    result = recv(**kwargs)
  File "zmq/backend/cython/socket.pyx", line 781, in zmq.backend.cython.socket.Socket.recv
  File "zmq/backend/cython/socket.pyx", line 817, in zmq.backend.cython.socket.Socket.recv
  File "zmq/backend/cython/socket.pyx", line 191, in zmq.backend.cython.socket._recv_copy
  File "zmq/backend/cython/socket.pyx", line 186, in zmq.backend.cython.socket._recv_copy
  File "zmq/backend/cython/checkrc.pxd", line 22, in zmq.backend.cython.checkrc._check_rc
zmq.error.Again: Resource temporarily unavailable
```

Looking at the hive-watcher which was feeding it, that stopped sending so whilst Docker is saying it is running, all further ZMQ communication seems to stop after that.

**Comment by agates** [comment]
Brian, this is 1) not a good bug report and 2) a dev branch.

We need a chat environment for this kind of thing

**Comment by brianoflondon** [comment]
Don'tcha just hate working with amateurs? 

In other news, when its not running in debug inside VSCode its very stable and even seems to deal nicely with the Testnet being flaky and just catches up as soon as it stops getting errors from Hive.

```
2021-06-14 11:22:10,426 INFO root MainThread : Transaction sent: 9da39c7adf4b0050872988e207ab955a89e74fe9 - Num urls: 8 - Size of Urls: 341 - Json size: 414
2021-06-14 11:22:10,427 INFO root MainThread : Overhead: 73
2021-06-14 11:22:10,427 INFO root MainThread : Task time: 0.96 - Queue size: 0
2021-06-14 11:22:10,427 INFO root MainThread : Finished a task: 9da39c7adf4b0050872988e207ab955a89e74fe9 - 0
2021-06-14 11:22:10,428 INFO root MainThread : Duration: 0.000 - URL in queue: https://feeds.buzzsprout.com/1588180.rss - URL List: 1
2021-06-14 11:22:10,430 INFO root MainThread : Duration: 0.961 - URL in queue: https://feeds.transistor.fm/a249d11a-772f-4a7f-99b0-e593506d3260 - URL List: 2
2021-06-14 11:22:10,432 INFO root MainThread : Duration: 0.963 - URL in queue: https://feeds.transistor.fm/william - URL List: 3
2021-06-14 11:22:10,434 INFO root MainThread : Duration: 0.964 - URL in queue: https://feeds.transistor.fm/dagens-bibelord-fra-bibel-no - URL List: 4
2021-06-14 11:22:10,436 INFO root MainThread : Duration: 0.966 - URL in queue: https://feeds.transistor.fm/psych-attack - URL List: 5
2021-06-14 11:22:10,438 INFO root MainThread : Duration: 0.968 - URL in queue: https://feeds.buzzsprout.com/768668.rss - URL List: 6
2021-06-14 11:22:11,599 INFO root MainThread : Duration: 0.971 - URL in queue: https://feeds.buzzsprout.com/1677436.rss - URL List: 7
2021-06-14 11:22:11,600 INFO root MainThread : Duration: 2.131 - URL in queue: https://feeds.transistor.fm/a249d11a-772f-4a7f-99b0-e593506d3260 - URL List: 7
2021-06-14 11:22:11,602 INFO root MainThread : Duration: 2.133 - URL in queue: https://feeds.transistor.fm/dagens-bibelord-fra-bibel-no - URL List: 7
2021-06-14 11:22:11,603 INFO root MainThread : Duration: 2.134 - URL in queue: https://feeds.transistor.fm/william - URL List: 7
2021-06-14 11:22:11,605 INFO root MainThread : Duration: 2.136 - URL in queue: https://feeds.buzzsprout.com/286788.rss - URL List: 8
2021-06-14 11:22:12,771 INFO root MainThread : Duration: 2.137 - URL in queue: https://feeds.buzzsprout.com/1405045.rss - URL List: 9
2021-06-14 11:22:12,772 INFO root MainThread : Size of Urls: 582
2021-06-14 11:22:12,772 INFO root MainThread : Received num_urls: 9
2021-06-14 11:22:13,162 WARNING beemapi.node MainThread : Error: Service Temporarily Unavailable
2021-06-14 11:22:13,162 WARNING beemapi.node MainThread : Retry RPC Call on node: https://testnet.openhive.network (1/5) 

2021-06-14 11:22:13,162 WARNING beemapi.node MainThread : Retrying in 0 seconds

2021-06-14 11:22:13,740 INFO root MainThread : Transaction sent: 91bc1824b63a3faa85ef0fa30dd0f6de5cf14e7a - Num urls: 9 - Size of Urls: 393 - Json size: 470
2021-06-14 11:22:13,740 INFO root MainThread : Overhead: 77
2021-06-14 11:22:13,740 INFO root MainThread : Task time: 0.97 - Queue size: 0
2021-06-14 11:22:13,740 INFO root MainThread : Finished a task: 91bc1824b63a3faa85ef0fa30dd0f6de5cf14e7a - 0
2021-06-14 11:22:13,795 INFO root MainThread : Duration: 0.000 - URL in queue: https://feeds.buzzsprout.com/1728548.rss - URL List: 1
2021-06-14 11:22:13,796 INFO root MainThread : Duration: 1.023 - URL in queue: https://feeds.transistor.fm/dagens-bibelord-fra-bibel-no - URL List: 2
2021-06-14 11:22:13,965 INFO root MainThread : Duration: 1.024 - URL in queue: https://feeds.buzzsprout.com/884488.rss - URL List: 3
```

**Comment by agates** [comment]
Sounds like a problem with your environment.

**Comment by brianoflondon** [comment]
This only happens on my Mac. My Raspberry Pi (costs less than the Mac's mouse) runs like a finely oiled diesel train. Closing this.
