### ISSUE TITLE
Installing podping-hivewriter in other projects.

### ISSUE THREAD

**Issue by brianoflondon** [Podcastindex-org/podping-hivewriter#53]
Trying to add `podping-hivewriter` in another project:

```
❯ poetry add podping-hivewriter
Using version ^1.2.6 for podping-hivewriter

Updating dependencies
Resolving dependencies... (16.4s)

Package operations: 1 install, 0 updates, 0 removals

  • Installing podping-hivewriter (1.2.6): Failed

  EnvCommandError

  Command ['/Users/gbishko/Library/Caches/pypoetry/virtualenvs/v4vapp-api-ext-cnYEIp-w-py3.9/bin/pip', 'install', '--no-deps', 'file:///Users/gbishko/Library/Caches/pypoetry/artifacts/04/c9/67/05ddce10054f44cd8158da6aa95b7b9798a58c1832b6d93f6ff8a61622/podping-hivewriter-1.2.6.tar.gz'] errored with the following return code 1, and output: 
  Processing /Users/gbishko/Library/Caches/pypoetry/artifacts/04/c9/67/05ddce10054f44cd8158da6aa95b7b9798a58c1832b6d93f6ff8a61622/podping-hivewriter-1.2.6.tar.gz
    Installing build dependencies: started
    Installing build dependencies: finished with status 'done'
    Getting requirements to build wheel: started
    Getting requirements to build wheel: finished with status 'done'
    Preparing metadata (pyproject.toml): started
    Preparing metadata (pyproject.toml): finished with status 'done'
  Building wheels for collected packages: podping-hivewriter
    Building wheel for podping-hivewriter (pyproject.toml): started
    Building wheel for podping-hivewriter (pyproject.toml): finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: /Users/gbishko/Library/Caches/pypoetry/virtualenvs/v4vapp-api-ext-cnYEIp-w-py3.9/bin/python /Users/gbishko/Library/Caches/pypoetry/virtualenvs/v4vapp-api-ext-cnYEIp-w-py3.9/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py build_wheel /var/folders/lr/3c_q67jx1xj89pdr229hq5jm0000gn/T/tmplntualb3
         cwd: /private/var/folders/lr/3c_q67jx1xj89pdr229hq5jm0000gn/T/pip-req-build-zo0rx633
    Complete output (25 lines):
    A setup.py file already exists. Using it.
    Traceback (most recent call last):
      File "/private/var/folders/lr/3c_q67jx1xj89pdr229hq5jm0000gn/T/pip-req-build-zo0rx633/setup.py", line 2, in <module>
        from setuptools import setup
    ModuleNotFoundError: No module named 'setuptools'
    Traceback (most recent call last):
      File "/Users/gbishko/Library/Caches/pypoetry/virtualenvs/v4vapp-api-ext-cnYEIp-w-py3.9/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
        main()
      File "/Users/gbishko/Library/Caches/pypoetry/virtualenvs/v4vapp-api-ext-cnYEIp-w-py3.9/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "/Users/gbishko/Library/Caches/pypoetry/virtualenvs/v4vapp-api-ext-cnYEIp-w-py3.9/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 261, in build_wheel
        return _build_backend().build_wheel(wheel_directory, config_settings,
      File "/private/var/folders/lr/3c_q67jx1xj89pdr229hq5jm0000gn/T/pip-build-env-z1fu1xi4/overlay/lib/python3.9/site-packages/poetry/core/masonry/api.py", line 68, in build_wheel
        return unicode(WheelBuilder.make_in(poetry, Path(wheel_directory)))
      File "/private/var/folders/lr/3c_q67jx1xj89pdr229hq5jm0000gn/T/pip-build-env-z1fu1xi4/overlay/lib/python3.9/site-packages/poetry/core/masonry/builders/wheel.py", line 78, in make_in
        wb.build()
      File "/private/var/folders/lr/3c_q67jx1xj89pdr229hq5jm0000gn/T/pip-build-env-z1fu1xi4/overlay/lib/python3.9/site-packages/poetry/core/masonry/builders/wheel.py", line 110, in build
        self._build(zip_file)
      File "/private/var/folders/lr/3c_q67jx1xj89pdr229hq5jm0000gn/T/pip-build-env-z1fu1xi4/overlay/lib/python3.9/site-packages/poetry/core/masonry/builders/wheel.py", line 162, in _build
        self._run_build_command(setup)
      File "/private/var/folders/lr/3c_q67jx1xj89pdr229hq5jm0000gn/T/pip-build-env-z1fu1xi4/overlay/lib/python3.9/site-packages/poetry/core/masonry/builders/wheel.py", line 190, in _run_build_command
        subprocess.check_call(
      File "/Users/gbishko/.pyenv/versions/3.9.4/lib/python3.9/subprocess.py", line 373, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/Users/gbishko/Library/Caches/pypoetry/virtualenvs/v4vapp-api-ext-cnYEIp-w-py3.9/bin/python', '/private/var/folders/lr/3c_q67jx1xj89pdr229hq5jm0000gn/T/pip-req-build-zo0rx633/setup.py', 'build', '-b', '/private/var/folders/lr/3c_q67jx1xj89pdr229hq5jm0000gn/T/pip-req-build-zo0rx633/build']' returned non-zero exit status 1.
    ----------------------------------------
    ERROR: Failed building wheel for podping-hivewriter
  Failed to build podping-hivewriter
  ERROR: Could not build wheels for podping-hivewriter, which is required to install pyproject.toml-based projects
  WARNING: You are using pip version 21.3.1; however, version 22.2.2 is available.
  You should consider upgrading via the '/Users/gbishko/Library/Caches/pypoetry/virtualenvs/v4vapp-api-ext-cnYEIp-w-py3.9/bin/python -m pip install --upgrade pip' command.
  

  at ~/.poetry/lib/poetry/utils/env.py:1183 in _run
      1179│                 output = subprocess.check_output(
      1180│                     cmd, stderr=subprocess.STDOUT, **kwargs
      1181│                 )
      1182│         except CalledProcessError as e:
    → 1183│             raise EnvCommandError(e, input=input_)
      1184│ 
      1185│         return decode(output)
      1186│ 
      1187│     def execute(self, bin, *args, **kwargs):


Failed to add packages, reverting the pyproject.toml file to its original content.
```

**Comment by agates** [comment]
Currently working on separating schema generation into their own projects so this project wont require a compiler.  It's a lot of work.
